
# Publish all joint states -----------------------------------
gripper_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

Slider1_effort_controller:
  type: effort_controllers/JointEffortController
  joint: Slider1
  # pid: {p: 100.0, i: 0.01, d: 10.0} # Adjust PID parameters as needed

# Slider2_effort_controller:
#   type: effort_controllers/JointEffortController
#   joint: Slider2
#   pid: {p: 100.0, i: 0.01, d: 10.0} # Adjust PID parameters as needed

  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    Slider1: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10