# PID gain settings for robotic gripper finger joint controlled via 
# gazebo_ros_control. Slider1 and Slider2 are both finger joints.
# Slider2 mimics and mirrors Slider1.
# Proper PID tuning is critical to prevent unstable behavior such as excessive
# joint drift or loss of ground contact during simulation.
# These parameters apply to Slider1 and Slider2 joints to ensure stable,
# realistic control of the robot in Gazebo.

gazebo_ros_control:
  pid_gains:
    # these gains are used by the gazebo_ros_control plugin
    Slider1:
      p: 1000.0
      i: 0.1
      d: 10.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    # the following gains are used by the gazebo_mimic_joint plugin
    Slider2:
      p: 1000.0
      i: 0.1
      d: 10.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
