
# Controller configuration for robotiq gripper Slider1 joint.
# - `gripper_joint_state_controller` publishes the current states (positions, velocities) 
#   of the gripper joints at 50 Hz.
# - `Slider1_effort_controller` sends direct effort commands to the Slider1 joint,
#   with constraints and timing parameters for smooth control and stopping behavior.

gripper_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

Slider1_effort_controller:
  type: effort_controllers/JointEffortController
  joint: Slider1

  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    Slider1: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10